spring.application.name=ridely
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=${DATABASE_DRIVER}
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations
spring.jpa.hibernate.ddl-auto=none
## Spring Docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
google.maps.api.key=

spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.sqs.endpoint=http://localhost:4566
aws.queue_url=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/driver-location-test-queue
spring.data.redis.host=localhost
spring.data.redis.port=6379

